### PR TITLE
fix: Fixes events update

### LINKED ISSUE #100: events not updated
events are [$watched](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L27) but they don't updated when [chart is rendered](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L67)

### PR DESCRIPTION
**Pull request by paul-shibanov**
Closes #100

### CODE REVIEW

File: src/angular-chartist.js [hunk 1]
```diff
@@ -40,6 +40,11 @@ class AngularChartistCtrl {
       this.chart.on(eventName, this.events[eventName]);
     });
   }
+  unbindEvents(events) {
```
Comment (paradox41) [inline src/angular-chartist.js]: Just need a new line here between methods please
